baseURL: "https://digital-austria.at/"
languageCode: "de-at"
defaultContentLanguage: "de"
defaultContentLang: "de"
title: "digital.austria"
# copyright: "https://digital-austria.at/"
paginate: 5
theme: PaperMod

enableGitInfo: true
enableRobotsTXT: true
# buildDrafts: false
# buildFuture: false
# buildExpired: false

googleAnalytics: G-P3R7P2EW0F

minify:
  disableXML: true
  minifyOutput: false

params:
  # env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: digital.austria
  description: "digital.austria - Verein zur Förderung der Informationstechnologie. Wir sind die Initiatoren von CoderDojo Tulln und CoderDojo Wien."
  keywords: [Blog, "Coding for Kids", "Programmieren für Kinder", "CoderDojo", "Tulln", "Wien", "Software", "Scratch", "micro:bit", "Python", ".Net", "Java", "C#", "Make Code"]
  author: Me
  # author: ["Daniel", "Carlo", "Rigerta", "Kathi"] # multiple authors
  images: ["/img/digital.austria_transparent.png", "/img/profile-image.web", "/img/logo.webp", "/img/coderdojo-tulln.png", "/img/coderdojo-wien.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShareButtons: []
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  mainSections:
  - posts
  
  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    # favicon: "<link / abs url>"
    # favicon16x16: "<link / abs url>"
    # favicon32x32: "<link / abs url>"
    # apple_touch_icon: "<link / abs url>"
    # safari_pinned_tab: "<link / abs url>"
    msapplication-TileColor: "#00aba9"
    
  label:
    text: " "
    icon: /img/digital.austria_banner.png
    iconHeight: 35

  profileMode:
    enabled: true # needs to be explicitly set
    title: digital.austria
    subtitle: "Wir fördern die Informationstechnologie"
    imageUrl: "img/profile-image.webp"
    imageWidth: 624
    imageHeight: 250
    imageTitle: "Logo von digital.austria"
    buttons:
      - name: über uns
        url: page/about
      - name: übungen
        url: https://coderdojo-linz.github.io/uebungsanleitungen/
      - name: sponsor
        url: page/sponsor
      - name: newsletter
        url: "http://eepurl.com/inFeMY"
    subImages:
      - imageTitle: "CoderDojo Wien"
        imageUrl: "img/coderdojo-wien.webp"
        url: "dojos/wien"
        width: 400
        height: 400
      - imageTitle: "CoderDojo Tulln"
        imageUrl: "img/coderdojo-tulln.webp"
        url: "dojos/tulln"
        width: 400
        height: 400


  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my blog

  socialIcons:
    - name: email
      url: "mailto:hallo@digital-austria.at"
    # - name: cv
    #   title: Newsletter
    #   url: "http://eepurl.com/inFeMY"
    - name: github
      url: "https://github.com/coderdojo-wien"
    - name: linkedin
      url: "https://www.linkedin.com/company/digital-austria"
    - name: facebook
      url: "https://www.facebook.com/digital.austria"
    - name: linkedin
      url: "https://www.linkedin.com/company/coderdojowien"
      title: "CoderDojo Wien on LinkedIn"
    - name: facebook
      url: "https://www.facebook.com/coderdojowien"
      title: "CoderDojo Wien on Facebook"
    - name: instagram
      title: "CoderDojo Wien on Instagram"
      url: "https://www.instagram.com/coderdojowien"
    - name: linkedin
      url: "https://www.linkedin.com/company/coderdojotulln"
      title: "CoderDojo Tulln on LinkedIn"
    - name: facebook
      url: "https://www.facebook.com/coderdojotulln"
      title: "CoderDojo Tulln on Facebook"
    - name: instagram
      url: "https://www.instagram.com/coderdojotulln"
      title: "CoderDojo Tulln on Instagram"
    - name: rss
      url: "index.xml"

  analytics:
    # google:
    #   SiteVerificationTag: "XYZabc"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    # hidden: true # hide everywhere but not in structured data
    # hiddenInList: true # hide on list pages and home
    # hiddenInSingle: true # hide on single page
    linkFullImages: false
  

  editPost:
    URL: "https://github.com/coderdojo-wien/digital-austria.github.io/blob/main/content"
    Text: "Ändern" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: about
      name: über uns
      url: /page/about/
      weight: 10
    - identifier: offering
      name: sponsor
      url: /page/sponsor/
      weight: 20
    - identifier: infos
      name: infos
      url: /infos/
      weight: 30
    - identifier: projects
      name: projekte
      url: /projects/
      weight: 40
    - identifier: posts
      name: posts
      url: /posts/
      weight: 50
    # - identifier: categories
    #   name: kategorien
    #   url: /categories/
    #   weight: 60
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 70
    - identifier: search
      name: suche
      url: /search
      weight: 80
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 90

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
